apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.analyticsService.servicename }}
  namespace: {{ .Values.namespace }}
  labels:
    app: analytics-service
    app.kubernetes.io/part-of: micro
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
  - name: http
    port: {{ .Values.analyticsService.port }}
    targetPort: {{ .Values.analyticsService.port }}
