apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: {{ .Values.namespace }}
  labels:
    app: order-service
data:
  SERVICE_NAME: "order-service"
  # Providing URLs matching what the Python code queries
  CATALOG_URL: "http://{{ .Values.catalogService.servicename }}:{{ .Values.catalogService.port }}"
  INVENTORY_URL: "http://{{ .Values.inventoryService.servicename }}:{{ .Values.inventoryService.port }}/inventory"
  NOTIFICATION_URL: "http://{{ .Values.notificationService.servicename }}:{{ .Values.notificationService.port }}"
