apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.orderService.deploymentname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: order-service
spec:
  replicas: {{ .Values.orderService.replicas }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.orderService.port }}"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10006
        fsGroup: 10006
      serviceAccountName: gar-puller-sa
      containers:
      - name: order-service
        image: {{ .Values.orderService.image }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        envFrom:
        # Automatically injects SERVICE_NAME, CATALOG_URL, INVENTORY_URL, NOTIFICATION_URL
        - configMapRef:
            name: order-service-config
        # Automatically injects ORDER_DB_DSN connection strings
        - secretRef:
            name: order-service-secret
