apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: order-service
type: Opaque
stringData:
  ORDER_DB_DSN: "dbname={{ .Values.db.name }} user={{ .Values.secrets.dbUser }} password={{ .Values.secrets.dbPassword }} host={{ .Values.db.host }} port={{ .Values.db.port }} sslmode={{ .Values.db.sslmode }}"
