apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: {{ .Values.namespace }}
  labels:
    app: order-service
data:
  SERVICE_NAME: "order-service"
  PORT: "{{ .Values.orderService.port }}"
  LOG_LEVEL: "info"
  PGHOST: {{ .Values.db.host | quote }}
  PGPORT: {{ .Values.db.port | quote }}
  PGDATABASE: {{ .Values.db.name | quote }}
  PGUSER: "microapp" 
  PGPASSWORD: "your_password" # Or bind via your secret file
  DB_SCHEMA: "orders"
  
  REDIS_ADDR: "{{ .Values.redis.servicename }}:{{ .Values.redis.port }}"
  
