apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: {{ .Values.namespace }}
  labels:
    app: payment-service
data:
  SERVICE_NAME: "payment-service"
  PORT: "{{ .Values.paymentService.port }}"
  LOG_LEVEL: "info"
  PGHOST: {{ .Values.db.host | quote }}
  PGPORT: {{ .Values.db.port | quote }}
  PGDATABASE: {{ .Values.db.name | quote }}
  PGUSER: "microapp" 
  PGPASSWORD: "your_password" # Or bind via your secret file
  DB_SCHEMA: "payments"
  DB_SSLMODE: {{ .Values.db.sslmode | quote }}
  REDIS_ADDR: "{{ .Values.redis.servicename }}:{{ .Values.redis.port }}"
